#!/usr/bin/env python3
"""
Simple launcher for Exostream Remote GUI

Usage:
    exostream-remote-gui
    
Or directly:
    python3 -m exostream.remote.gui
"""

from exostream.remote.gui import main

if __name__ == "__main__":
    main()

